name: mkdocs
channels:
  - pkgs/main
dependencies:
  - python
  - conda-libmamba-solver
  - pip
  - pip:
      - pip
      - mkdocs-techdocs-core
      # Dev
      - black
      - flake8
      - ipykernel
      - mypy
      - notebook
      - pydocstyle
      - pylint
