name: mkdocs
channels:
  - pkgs/main
dependencies:
  - python
  - pip
  - pip:
      # dev
      - ipykernel
      - mypy
      - notebook
      - pydocstyle
      # mkdocs
      - mkdocs-techdocs-core
